name: Java CI with Gradle

on:
  push:
    branches: [ main, testng, junit4, junit5, junit-platform ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Test on JDK 11
    runs-on: ubuntu-20.04
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2

    - name: Run tests with Gradle
      run: gradle test --no-daemon --console=plain

    - name: Upload test reports
      uses: actions/upload-artifact@v3
      with:
        name: test-report-${{ github.ref_name }}
        path: build/reports/tests/
